### ISSUE TITLE
Print roster displays table towards the middle of the print page instead of the top

### ISSUE THREAD

**Issue by zeroClassSOLDIER** [spsprinkles/event-registration#3]
@mikewil1977 I tried adjusting the CSS settings in the admin.ts file with limited results. I removed the line with position, left, and top, but there was no effect. It is still displayed in the middle. The line that sets the visibility to hidden has an effect in body but not much else.

See PNG and JPG files below:
![print_roster](https://user-images.githubusercontent.com/84786032/145890225-12700f9a-65bb-4e81-8479-3f5494a80bfa.jpg)
![view_print_2](https://user-images.githubusercontent.com/84786032/145890385-3648b1ea-8abd-4691-ad8a-134acbf84a41.png)

**Comment by gunjandatta** [comment]
PR #4 fixed this issue.
